// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyW2JmJmA7f87T5P9b_uQqjoPduw7yIg',
    appId: '1:442967005775:web:c12ef069d8c2494ebfa83a',
    messagingSenderId: '442967005775',
    projectId: 'signin-38756',
    authDomain: 'signin-38756.firebaseapp.com',
    storageBucket: 'signin-38756.appspot.com',
    measurementId: 'G-0PBHT9WLKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwxLE3WZHdPD4zXUTEyyDQ6gYbNp6kmE',
    appId: '1:442967005775:android:ed8ded38ba4f38f7bfa83a',
    messagingSenderId: '442967005775',
    projectId: 'signin-38756',
    storageBucket: 'signin-38756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBjtT_IxIQ1LQCFqnuemsT3bodiN-nJVc',
    appId: '1:442967005775:ios:118a704f24d8d3ccbfa83a',
    messagingSenderId: '442967005775',
    projectId: 'signin-38756',
    storageBucket: 'signin-38756.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBjtT_IxIQ1LQCFqnuemsT3bodiN-nJVc',
    appId: '1:442967005775:ios:660252deb28bf408bfa83a',
    messagingSenderId: '442967005775',
    projectId: 'signin-38756',
    storageBucket: 'signin-38756.appspot.com',
    iosBundleId: 'com.example.signin.RunnerTests',
  );
}
